apiVersion: apps/v1
kind: Deployment
metadata:
  name: parttime-server-deployment
  labels:
    app: server-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-1
  template:
    metadata:
      labels:
        app: server-1
    spec:
      containers:
      - name: server-1
        image: nginx:1.14.2
        ports:
        - containerPort: 30092
---

apiVersion: v1
kind: Service
metadata:
  name: parttime-server-service
spec:
  selector:
    app.kubernetes.io/name: server-1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 30092