name: CI/CD pipeline for express js app
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Log in docker hub
              uses: docker/login-action@v2
              with:
                registry: https://index.docker.io/v1/
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}  

            - name: Build docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/parttime-server:v1 .

            - name: Push docker image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/parttime-server:v1    